### ISSUE TITLE
Languages\BrazilianPortuguese

### ISSUE THREAD

**Issue by emalherbi** [felicienfrancois/node-innosetup-compiler#1]
Hi.

I'm a Brazilian guy and I have doubt about the node-innosetup-compiler.

In my Iss code, I used.

```sh
Name: "brazilianportuguese"; MessagesFile: "compiler:Languages\BrazilianPortuguese.isl"
```

But the shell showed the following error.

```sh
Running "innosetup-compiler:my_update" (innosetup-compiler) task

[ISPP] Preprocessing.Error on line 30 in D:\www\web_comboio\branches\app\script\update.iss: Couldn't open include file "
D:\www\web_comboio\branches\node_modules\innosetup-compiler\bin\Languages\BrazilianPortuguese.isl": O sistema n?o pode e
ncontrar o caminho especificado.
Compile aborted.
Warning: Task "innosetup-compiler:my_update" failed. Use --force to continue.

Aborted due to warnings.
```

When I use the specific path of my machine for the Brazilian language, it works correctly.

```sh
Name: "brazilianportuguese"; MessagesFile: "C:\Program Files (x86)\Inno Setup 5\Languages\BrazilianPortuguese.isl"
```

But I wouldn't want to use that specific path. Because, if I change the machine this path can change.

Can you help-me?

**Comment by felicienfrancois** [comment]
Sorry for answering so late, I had not catched the notification.
You can put the language file in your project dir and set MessagesFile to the relative path:
```
Name: "brazilianportuguese"; MessagesFile: "path/to/BrazilianPortuguese.isl"
```

**Comment by felicienfrancois** [comment]
I could also ship all the translation files in the module. I'll try

**Comment by felicienfrancois** [comment]
Languages files added in last version (5.5.52)

**Comment by emalherbi** [comment]
I can´t test now, but tks man... I'll wait for the new version...
