### ISSUE TITLE
Progress or Error feedback?

### ISSUE THREAD

**Issue by chadananda** [felicienfrancois/node-innosetup-compiler#2]
Is there supposed to be any feedback for progress or errors? The script seems to do absolutely nothing at all and it's unclear just what, if anything, is happening.

**Comment by chadananda** [comment]
I suspect I have a Wine issue. When cd to the 'bin' directory and run the ISCC.exe with "wine ISCC.exe", I get the Wine error:

fixme:process:SetProcessDEPPolicy (1): stub
err:macdrv:process_attach Failed to start Cocoa app main loop
err:macdrv:process_attach Failed to start Cocoa app main loop
...

**Comment by felicienfrancois** [comment]
Can you tell me how you're using it ? command line, via nodejs or using grunt ?

You may not have any feedback in command line mode. I'll try to fix this soon.

In the meantime, you can try to use the nodejs mode and print the error from the callback:
```
require("innosetup-compiler")("path/to/your/innoscript.iss", {}, function(error) {
    if (error) console.error(error);
});
```

Tell me if you get thoose wine errors.
I'll test it on my macbook in the next days and try to reproduce it.

**Comment by felicienfrancois** [comment]
I published a new version (5.5.52) with 2 new options which can help you debug
https://github.com/felicienfrancois/node-innosetup-compiler

You may have to clear your npm cache to update.

**Comment by felicienfrancois** [comment]
I have the same issue on my macbook with wine 1.6.2 (installed with homebrew), in both gui and normal mode.

I updated wine to devel version (1.7.35) and it worked successfully.
```shell
brew install wine --devel
```

**Comment by chadananda** [comment]
Yes, it seems to have been a version issue with Wine and ISCC.exe. I also tried an older version of ISCC.exe and it worked seamlessly.
