### ISSUE TITLE
Error while compile

### ISSUE THREAD

**Issue by Tolerant** [felicienfrancois/node-innosetup-compiler#5]
Hi, 
I catch error 
`Error on line 28 in D:\...\..\file.iss: Resource update error: EndUpdateResource failed (110)`
After 3-4 attempts returns,  success.
Here my iss file (i compile him with native inno-setup gui):
```

; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Some_Name"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "SomeCompany"
#define MyAppURL "https://some.site/"
#define MyAppExeName "Some_Name.exe"
#define MyAppSystem "win32-ia32"
#define MyAppDirName "dist\MyAppName"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{7D55623D-400C-4E2D-AAF4-41218D604617}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={pf}\{#MyAppName}
DisableProgramGroupPage=yes
OutputDir=.\dist
OutputBaseFilename=Some_Name_{#MyAppVersion}_{#MyAppSystem}
SetupIconFile=icon.ico
Compression=lzma
SolidCompression=yes

[Languages]
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}";

[Files]
Source: "{#MyAppDirName}-{#MyAppSystem}\MyAppName.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#MyAppDirName}-{#MyAppSystem}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{commonprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

```

**Comment by felicienfrancois** [comment]
It seems to fail when applying the icon to the setup bin.
But I have no clue on what happened.

I will upgrade innosetup binaries (currently 5.5.6, newly available are 5.5.8), it may fix the issue ...

**Comment by felicienfrancois** [comment]
v5.5.8 published to npm, can you test it out?

**Comment by Tolerant** [comment]
@felicienfrancois 

About Inno Setup
---------------------------
Inno Setup Compiler version 5.5.8 (a)

**Comment by Tolerant** [comment]
@felicienfrancois 
Thank for your replay,  i test it on 5.5.8 version.
Error still return.
Screenshot: http://take.ms/sGqoU

**Comment by felicienfrancois** [comment]
OK, too bad :S
But it's probably not due to innosetup nor innosetup-compiler (which is just a wrapper).
Innosetup fail to edit resources of the setup binary. It is probably due to another process accessing or locking the file.
Do you have any file watcher runing?
You should try to execute only innosetup-compiler by hand, out of tests or continuous integration (which may watch or access the file)
Then if it still don't work, the other possible source of issue may be the bash you use or the version of nodejs.

**Comment by Tolerant** [comment]
I checked my project for any watcher.
No watcher found.
native gui resolve same error: http://take.ms/PZ2qz
if re-run error no return...sad...

-
Sorry for my english

**Comment by felicienfrancois** [comment]
OK, so it's not related to this project (which is just a wrapper, not affiliated with the original innosetup software).

It seems other people got this error and solve it by disabling their antivirus program (which is actually a file watcher AND locker)
http://stackoverflow.com/questions/1437844/how-to-fix-inno-setup-error-endupdateresource-failed-110

**Comment by Tolerant** [comment]
It's right!
i find my watcher!
https://www.getsync.com/ block him.
After stop sync - problem closed.
Thank for your help and good feedback!
have a nice day!
